services:
  - type: web
    name: brainly-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: MONGODB_URI
        sync: false  # This will require manual setting in Render dashboard
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
