services:
  - type: web
    name: brainly-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://pratik:pratik%40123@cluster0.ret80.mongodb.net/brainly
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
