services:
  - type: web
    name: brainly-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://gautampratik483:ToX8NF7rkJk5XtGM@cluster0.a1h3q.mongodb.net/brainly?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
